image: gradle:jdk17

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  NODE_ENV: "test"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd backend
    - GRADLE_USER_HOME="$(pwd)/.gradle"
    - export GRADLE_USER_HOME
    - gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

frontend-test:
  image: node:18-alpine
  stage: test
  timeout: 20m
  script:
    - cd frontend
    - yarn install
    - yarn test --no-watch
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: frontend/coverage/cobertura-coverage.xml
    paths:
      - frontend/coverage/
  cache:
    key: 
      files:
        - frontend/yarn.lock
    paths:
      - frontend/node_modules/
    policy: pull-push
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

deploy:
  stage: deploy
  script:
    - echo "Add your deployment commands here"
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual