services:
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose backend on port 8080
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge